site: Personal Blog
title: f4him
greetings: fahim shahriar 
description: >-
  Welcome to my blog. Here I write about the solutions of the problems I face everyday while working so that I find them easily when I face them again. I am very glad if these posts help you in any way.
lang: en-US
timezone:  Europe/Rome
repo: https://github.com/p0wex/Gesko # site repo [optional]
data-theme: dark # default theme "dark" | "light"

author:
  name: f4him
  bio: just a minimalist, personal blog
  userpicture: 
  username: Fahim Shahriar # general username
  github: f4him # github username
  twitter: Fahim Shahriar # twitter username
  email: shahriarfahim23@email.com # email adress

# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900

# URL settings
url: "https://f4him.github.io"
# url: "http://localhost:4000" 
baseurl: ""
permalink: pretty

# local
# baseurl: "" # 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed


future: true
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


